<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Ruxsatlar',
    'Access denied!' => 'Ruxsat berilmagan',
    'Admin' => 'Admin',
    'Are you sure you want to delete this item?' => 'Siz rostdan ham shu malumotni o\'chirmoqchimisiz?',
    'Auth Assignment' => 'Ruxsat',
    'Auth Assignments' => 'Ruxsatlar',
    'Auth Item' => 'Role',
    'Auth Item Child' => 'Permission',
    'Auth Item Children' => 'Permissionlar',
    'Auth Items' => 'Rollar',
    'Brith Date' => 'Tug\'ilgan sana',
    'Child' => 'Bola',
    'Create Auth Assignment' => 'Ruxsat yaratish',
    'Create Auth Item' => 'Rule yaratish',
    'Create Auth Item Child' => 'Permission yaratish',
    'Create Hr Employee' => 'Xodim yaratish',
    'Create User' => 'Foydalanuvchi yaratish',
    'Created At' => 'Yaratilgan muddat',
    'Created By' => 'Kim tomonidan',
    'Data' => 'Malumot',
    'Delete' => 'O\'chirish',
    'Description' => 'Izoh',
    'Email' => 'Email',
    'Fish' => 'Fish',
    'Hr Employees' => 'Xodimlar',
    'ID' => 'ID',
    'Images' => 'Shaxsiy rasm',
    'Item Name' => 'Ruxsat nomi',
    'Login yoki Parol xato!' => 'Login yoki Parol xato',
    'Name' => 'Nomi',
    'Not Found' => 'Topilmadi',
    'Not Saved' => 'Saqlanmadi',
    'Parent' => 'Ota onasi',
    'Pasport Series' => 'Paport seriya',
    'Password' => 'Parol',
    'Phone' => 'Telefon nomer',
    'Profile' => 'Shaxsiy profile',
    'Reset' => 'Yangilash',
    'Rule Name' => '',
    'Save' => 'Saqlash',
    'Search' => 'Qidirish',
    'Select Child' => 'Bola tanlash',
    'Select Parent' => 'Ota ona tanlash',
    'Select...' => 'Tanlash',
    'Settings' => 'Sozlamalar',
    'Simple' => 'Oddiy',
    'Status' => 'Xolati',
    'Success Saved' => 'Saqlandi',
    'The requested page does not exist.' => '',
    'Type' => 'Turi',
    'Update' => 'Yangilash',
    'Update Auth Assignment: {name}' => 'Ruxsatlarni yangilash {name}',
    'Update Auth Item Child: {name}' => 'Permission yangilash {name}',
    'Update Auth Item: {name}' => 'Ruxsat yangilash {name}',
    'Update Hr Employee: {name}' => 'Xodim yangilash {name}',
    'Update User: {name}' => 'Foydalanuvchini yangilash',
    'Updated At' => 'Yangilash vaqti',
    'Updated By' => 'Kim tomonidan yangilandi',
    'User ID' => 'Foydalanuvchi ID',
    'User Select' => 'Foydalanuvchini tanlash',
    'Username' => 'Foydalanuvchi login',
    'Users' => 'Foydalanuvchilar',
];
