<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => '',
    'Access denied!' => '',
    'Admin' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Assignment' => '',
    'Auth Assignments' => '',
    'Auth Item' => '',
    'Auth Item Child' => '',
    'Auth Item Children' => '',
    'Auth Items' => '',
    'Brith Date' => '',
    'Child' => '',
    'Create Auth Assignment' => '',
    'Create Auth Item' => '',
    'Create Auth Item Child' => '',
    'Create Hr Employee' => '',
    'Create User' => '',
    'Created At' => '',
    'Created By' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Fish' => '',
    'Hr Employees' => '',
    'ID' => '',
    'Images' => '',
    'Item Name' => '',
    'Login yoki Parol xato!' => '',
    'Name' => '',
    'Not Found' => '',
    'Not Saved' => '',
    'Parent' => '',
    'Pasport Series' => '',
    'Password' => '',
    'Phone' => '',
    'Profile' => '',
    'Reset' => '',
    'Rule Name' => '',
    'Save' => '',
    'Search' => '',
    'Select Child' => '',
    'Select Parent' => '',
    'Select...' => '',
    'Settings' => '',
    'Simple' => '',
    'Status' => '',
    'Success Saved' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Update' => '',
    'Update Auth Assignment: {name}' => '',
    'Update Auth Item Child: {name}' => '',
    'Update Auth Item: {name}' => '',
    'Update Hr Employee: {name}' => '',
    'Update User: {name}' => '',
    'Updated At' => '',
    'Updated By' => '',
    'User ID' => '',
    'User Select' => '',
    'Username' => '',
    'Users' => '',
];
